version: "3.8"

services:
  app:
    env_file:
      .env
    build: .
    ports:
      - 8000:8080
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}